.\" mkinitramfs.cmdline(7) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 7, 2023
.Dt MKINITRAMFS.CMDLINE 7
.Os
.\" ==================================================================
.Sh NAME
.Nm mkinitramfs.cmdline
.Nd mkinitramfs' kernel command-line parameters
.\" ==================================================================
.Sh DESCRIPTION
The
.Xr mkinitramfs 8
utility provides a way to control configuration dynamically via kernel
parameters without needing to regenerate initramfs image.
.\" ------------------------------------------------------------------
.Ss General Parameters
.Bl -tag -width Ds -compact
.It Sy debug Ns = Ns Op 1
Enable debug mode.
.Pp
.It Sy break Ns = Ns Aq BREAKPOINT
Specify breakpoint where shell should be invoked.
Useful for debugging.
.Pp
List of builtin breakpoints:
.Bl -tag -width XX -compact
.It - boot
.It - root
.El
.Pp
Hooks can provide their own breakpoints.
See source code of hooks for more information.
.Pp
.It Sy root Ns = Ns Aq UUID | LABEL | /dev/* | PARTUUID
Specify which way initramfs will use to look up root filesystem.
.Pp
.Bl -tag -width PARTUUID -compact
.It UUID
Lookup device by uuid.
.It LABEL
Lookup device by label.
.It /dev/*
Lookup device by full path.
.It PARTUUID
Lookup device by partition uuid.
.El
.Pp
Initramfs must contain
.Sy blkid
utility for ability to use UUID, LABEL, PARTUUID.
.Sy Note :
PARTUUID only supported in
.Sy util-linux Ns '
.Xr blkid 8 .
.Pp
.It Sy root_type Ns = Ns Aq TYPE
.It Sy rootfstype Ns = Ns Aq TYPE
Explicitly set root filesystem type.
Kernel must support specified type.
.Pp
.It Sy rootdelay Ns = Ns Aq DELAY
Specify maximum number of seconds to wait for root device instead of
the default 30 seconds.
.Pp
.It Sy root_opts Ns = Ns Aq OPTS
.It Sy rootflags Ns = Ns Aq OPTS
See
.Xr fstab 5
fourth field.
.El
.\" ------------------------------------------------------------------
.Ss Hooks Parameters
Initramfs must contain appropriate hooks for ability to use below
parameters.
.Pp
The parameters for
.Sy LVM
hook are as follows:
.Bl -tag -width Ds
.It Sy lvm_tag Ns = Ns Aq TAG
Specify LVM tag which will be used to trigger LVM.
.Pp
This option will be ignored if
.Sy lvm_name Ns / Ns Sy lvm_group
was specified.
.It Sy lvm_name Ns = Ns Aq NAME
Specify LVM name which will be used to trigger LVM.
.Pp
.Sy lvm_group
(see below) must be specified.
.It Sy lvm_group Ns = Ns Aq GROUP
Specify LVM group which will be used to trigger LVM.
.It Sy lvm_discard Ns = Ns Op 1
Pass
.Em issue_discards
to LVM.
Leave empty to disable.
Useful for SSD's.
.El
.Pp
The parameters for
.Sy LUKS
hook are as follows:
.Bl -tag -width Ds
.It Sy luks_name Ns = Ns Aq NAME
Specify which name will be registered to mapping table after
.Xr cryptsetup 8
unlocks LUKS root.
.It Sy luks_root Ns = Ns Aq UUID | LABEL | /dev/* | PARTUUID
See
.Sy root
(above) for details.
.It Sy luks_discard Ns = Ns Op 1
Pass
.Dq --allow-discards
to
.Xr cryptsetup 8 .
Leave empty to disable.
.Pp
Useful for SSD's, but you must know that security will be decreased.
.El
.\" ==================================================================
.Sh EXAMPLES
Specify
.Sy root
option argument:
.Bd -literal -offset indent
vmlinuz initrd=\einitramfs root=/dev/sda1 [...]
.Ed
.Pp
Disable
.Dq discards
for
.Sy LUKS
and
.Sy LVM :
.Bd -literal -offset indent
vmlinuz initrd=\einitramfs luks_discard= lvm_discard= [...]
.Ed
.Pp
Pass arguments to real init:
.Bd -literal -offset indent
vmlinuz initrd=\einitramfs [...] -- arguments
.Ed
.\" ==================================================================
.Sh SEE ALSO
.Xr mkinitramfs.config 5 ,
.Xr mkinitramfs.hooks 7 ,
.Xr mkinitramfs 8
.\" vim: cc=72 tw=70
.\" End of file.
