# systemd-udevd init hook
# See COPYING for license terms and COPYRIGHT for notices.

# shellcheck shell=sh
#
# https://www.shellcheck.net/wiki/SC2154
# shellcheck disable=2154

if [ "$break" = "systemd-udevd" ]; then
	info "break before systemd-udevd.init"

	sh
fi

/lib/systemd/systemd-udevd -dN never
udevadm trigger -c add -t subsystems
udevadm trigger -c add -t devices
udevadm settle

# vim: ft=sh cc=72 tw=70
# End of file.
