# mdev init hook
# See COPYING and COPYRIGHT files for corresponding information.

# shellcheck shell=sh
#
# https://www.shellcheck.net/wiki/SC2154
# https://www.shellcheck.net/wiki/SC2034
# shellcheck disable=2154,2034

if [ "$break" = mdev ]; then
	print "break before mdev.init"

	sh
fi

mdev -s
mdev -df 2> /dev/null & mdev_pid="$!"

find /sys/devices -name uevent | while read -r uevent; do
	printf add > "$uevent"
done 2> /dev/null

# vim: ft=sh cc=72 tw=70
# End of file.
