name: IRC Notification CI
on: [push, pull_request]

jobs:

  notify:
    runs-on: ubuntu-latest

    steps:

      - name: Push Notification
        uses: Gottox/irc-message-action@v2
        if: github.event_name == 'push'
        with:
          channel: '#zeppe-lin'
          nickname: zeppbot
          message: |-
            ${{ github.actor }} pushed ${{ github.event.repository.name }}:${{ github.ref_name || github.event.ref }} -- ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message, '
            ') }}

      - name: PR Notification
        uses: Gottox/irc-message-action@v2
        if: github.event_name == 'pull_request'
        with:
          channel: '#zeppe-lin'
          nickname: zeppbot
          message: |-
            ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}

# End of file.
