name: IRC Notification CI
on: [push, pull_request, create]

jobs:

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Push Notification
        uses: Gottox/irc-message-action@v2
        if: github.event_name == 'push'
        with:
          channel: '#zeppe-lin'
          nickname: zeppbot
          message: |-
            ${{ github.actor }} pushed ${{ github.event.repository.name }}:${{ github.ref_name || github.event.ref }}
            ${{ join(github.event.commits.*.message, '
            ') }}
            ${{ github.event.compare }}

      - name: Pull Request Notification
        uses: Gottox/irc-message-action@v2
        if: github.event_name == 'pull_request'
        with:
          channel: '#zeppe-lin'
          nickname: zeppbot
          message: |-
            ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}

      - name: Tag Created Notification
        uses: Gottox/irc-message-action@v2
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: '#zeppe-lin'
          nickname: zeppbot
          message: |-
            ${{ github.actor }} tagged ${{ github.repository }}:${{ github.event.ref }}

# End of file.
