# See COPYING and COPYRIGHT files for corresponding information.

# shellcheck shell=sh
#
# https://www.shellcheck.net/wiki/SC2154
# shellcheck disable=2154

if [ "$break" = proc ]; then
  print "break before proc.init"

  sh
fi

command -v device-helper > /proc/sys/kernel/hotplug

# Prepare for fork bomb!
find /sys/devices -name uevent | while read -r uevent; do
  printf add > "$uevent"
done 2> /dev/null

# vim:ft=sh:sw=2:ts=2:sts=2:et:cc=72:tw=70
# End of file.
